#####  CONCATENATE and make a array 

In [3]:
import numpy as np
import pandas as pd
from pandas import Series 
from pandas import DataFrame 

In [4]:
a=np.arange(1,10).reshape(3,3)

In [5]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.concatenate([a,a])     #concatenate two list in array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.concatenate([a,a,a])     

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.concatenate([a,a],axis=0)           #vertical stack

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.concatenate([a,a],axis=1)     #horixontal concate

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [10]:
s1=Series([1,2,3],index=list('tuv'))
s2=Series([10,20,30],index=list('xyz'))


In [11]:

s1

t    1
u    2
v    3
dtype: int64

In [12]:
s2

x    10
y    20
z    30
dtype: int64

In [13]:
pd.concat([s1,s2])          #concate in series

t     1
u     2
v     3
x    10
y    20
z    30
dtype: int64

In [14]:
pd.concat([s1,s2],axis=1)            # dont work on vstack in series and show warning

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0     1
t  1.0   NaN
u  2.0   NaN
v  3.0   NaN
x  NaN  10.0
y  NaN  20.0
z  NaN  30.0

### Dealing with NULL values

In [15]:
s=Series([1,2,np.nan,np.nan,5,6,np.nan])        #if nan values then it convert it into float

In [16]:
s

0    1.0
1    2.0
2    NaN
3    NaN
4    5.0
5    6.0
6    NaN
dtype: float64

In [17]:
s.isnull()           #bool

0    False
1    False
2     True
3     True
4    False
5    False
6     True
dtype: bool

In [18]:
s.notnull()      #dirct convrt in bool

0     True
1     True
2    False
3    False
4     True
5     True
6    False
dtype: bool

In [19]:
fb1=Series({'a':np.nan,'b':2,'c':1,'d':np.nan,'e':np.nan})
fb2=Series({'a':3,'b':2,'c':5,'d':5,'e':3})

In [20]:
fb1



a    NaN
b    2.0
c    1.0
d    NaN
e    NaN
dtype: float64

In [21]:
fb2

a    3
b    2
c    5
d    5
e    3
dtype: int64

In [22]:
c=fb1.isnull()
c

a     True
b    False
c    False
d     True
e     True
dtype: bool

In [23]:
fb1+fb2      #data loss so we need to remove null

a    NaN
b    4.0
c    6.0
d    NaN
e    NaN
dtype: float64

In [24]:
fb3=Series(list(np.where(c,fb2,fb1)),index=fb1.index)
fb3

a    3.0
b    2.0
c    1.0
d    5.0
e    3.0
dtype: float64

In [29]:
FB1=DataFrame(fb1)
FB2=DataFrame(fb2)           #not work in more than two we need to step by step concate
FB3=DataFrame(fb3)
FB=(pd.concat([FB1,FB2,FB3],axis=1))
FB

0  0    0
a  NaN  3  3.0
b  2.0  2  2.0
c  1.0  5  1.0
d  NaN  5  5.0
e  NaN  3  3.0

In [30]:
(FB3+FB2)/2

0
a  3.0
b  2.0
c  3.0
d  5.0
e  3.0

In [31]:
FB1.isnull().sum()       #count of null values

0    3
dtype: int64

In [32]:
FB1.dropna()         #drop all the null values

0
b  2.0
c  1.0

In [41]:
FB1.fillna(0)      #fill null value as 0 or whatever valuen we want to fill

0
a  0.0
b  2.0
c  1.0
d  1.0
e  1.0

In [24]:
FB1.fillna(10) 

0
a  10.0
b   2.0
c   1.0
d  10.0
e  10.0

In [95]:
a=DataFrame({'A':[1,np.nan,np.nan,np.nan],'B':[2,5,8,np.nan],'C':[3,6,np.nan,np.nan]})
a                                                           #method 1 dictionary method

A    B    C
0  1.0  2.0  3.0
1  NaN  5.0  6.0
2  NaN  8.0  NaN
3  NaN  NaN  NaN

In [105]:
a=DataFrame(np.array([[1,2,3],[np.nan,5,6],[np.nan,8,np.nan],[np.nan,np.nan,np.nan]]),columns=list('abc'))   #method 2 array method
a

a    b    c
0  1.0  2.0  3.0
1  NaN  5.0  6.0
2  NaN  8.0  NaN
3  NaN  NaN  NaN

In [24]:
s1=Series([1,np.nan,np.nan,np.nan])
s2=Series([2,5,8,np.nan])                        #method 3        series method
s3=Series([3,6,np.nan,np.nan])
df1=DataFrame()
df1['A']=s1
df1['B']=s2
df1['C']=s3
df1

A    B    C
0  1.0  2.0  3.0
1  NaN  5.0  6.0
2  NaN  8.0  NaN
3  NaN  NaN  NaN

In [110]:
df1.isnull()

A      B      C
0  False  False  False
1   True  False  False
2   True  False   True
3   True   True   True

In [117]:
df1.isnull().sum()

A    3
B    1
C    2
dtype: int64

In [112]:
df1.notnull().sum()

A    1
B    3
C    2
dtype: int64

In [115]:
df1.info                     #also give not null value

<bound method DataFrame.info of      A    B    C
0  1.0  2.0  3.0
1  NaN  5.0  6.0
2  NaN  8.0  NaN
3  NaN  NaN  NaN>

In [120]:
df1.dropna()         #work as any fun

A    B    C
0  1.0  2.0  3.0

In [123]:
df1.dropna(how='any') 

A    B    C
0  1.0  2.0  3.0

In [125]:
df1.dropna(how='all') #all fun

A    B    C
0  1.0  2.0  3.0
1  NaN  5.0  6.0
2  NaN  8.0  NaN

In [130]:
df1.dropna(how='any',axis=1)       #all column have null value

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [131]:
df1.dropna(how='all',axis=1)

A    B    C
0  1.0  2.0  3.0
1  NaN  5.0  6.0
2  NaN  8.0  NaN
3  NaN  NaN  NaN

In [134]:
df1.dropna(thresh=1)       #thresh is with respect to not null values thresh=1 then check evenif row have more 
                            #than or equal to 1 not null value then it will remain that and remove 

A    B    C
0  1.0  2.0  3.0
1  NaN  5.0  6.0
2  NaN  8.0  NaN

In [137]:
df1.dropna(thresh=2)  #thresh is with respect to not null values thresh=2 then check evenif row have more 
                            #than or equal to 2 not null value then it will remain that and remove rest

A    B    C
0  1.0  2.0  3.0
1  NaN  5.0  6.0

In [138]:
df1.dropna(thresh=3) 

A    B    C
0  1.0  2.0  3.0

In [139]:
df1.dropna(thresh=1,axis=1)    #column wise

A    B    C
0  1.0  2.0  3.0
1  NaN  5.0  6.0
2  NaN  8.0  NaN
3  NaN  NaN  NaN

In [140]:
df1.dropna(thresh=2,axis=1) 

B    C
0  2.0  3.0
1  5.0  6.0
2  8.0  NaN
3  NaN  NaN

In [143]:
df1.fillna(0)

A    B    C
0  1.0  2.0  3.0
1  0.0  5.0  6.0
2  0.0  8.0  0.0
3  0.0  0.0  0.0

In [145]:
df1.fillna(method='ffill')   #forward fill

A    B    C
0  1.0  2.0  3.0
1  1.0  5.0  6.0
2  1.0  8.0  6.0
3  1.0  8.0  6.0

In [146]:
df1.fillna(method='bfill')  #fillna doesn't have nearest fill only have ffill or bfill

A    B    C
0  1.0  2.0  3.0
1  NaN  5.0  6.0
2  NaN  8.0  NaN
3  NaN  NaN  NaN

In [150]:
df1=df1.reindex(range(5))
df1

A    B    C
0  1.0  2.0  3.0
1  NaN  5.0  6.0
2  NaN  8.0  NaN
3  NaN  NaN  NaN
4  NaN  NaN  NaN

In [153]:
df1.iloc[4]=10         #iloc for index
df1

A     B     C
0   1.0   2.0   3.0
1   NaN   5.0   6.0
2   NaN   8.0   NaN
3   NaN   NaN   NaN
4  10.0  10.0  10.0

In [154]:
df1.dropna(thresh=1)  #min 1 not null value is not seperate rest will seprate

A     B     C
0   1.0   2.0   3.0
1   NaN   5.0   6.0
2   NaN   8.0   NaN
4  10.0  10.0  10.0

In [152]:
df1.fillna(method='bfill')

A     B     C
0   1.0   2.0   3.0
1  10.0   5.0   6.0
2  10.0   8.0  10.0
3  10.0  10.0  10.0
4  10.0  10.0  10.0

### How to deal with Duplicate 

In [155]:
d=DataFrame({'key1':['a','a','a','b','b'],'key2':[2,2,3,3,3]})

In [156]:
d

key1  key2
0    a     2
1    a     2
2    a     3
3    b     3
4    b     3

In [162]:
d.duplicated()    #duplicate value as true it check duplicacy from top to bottom on row

0    False
1     True
2    False
3    False
4     True
dtype: bool

In [171]:
d.duplicated(['key1'])   #check duplicate on basis of key1 column from top to bottom

0    False
1     True
2     True
3    False
4     True
dtype: bool

In [172]:
d.duplicated(['key2'])

0    False
1     True
2    False
3     True
4     True
dtype: bool

In [176]:
d.duplicated(keep='last') #check from bottom to top row wise

0     True
1    False
2    False
3     True
4    False
dtype: bool

In [175]:
d.drop_duplicates()     # it drops the duplicated values

key1  key2
0    a     2
2    a     3
3    b     3

In [177]:
d.drop_duplicates(['key2']) 

key1  key2
0    a     2
2    a     3

In [180]:
d.drop_duplicates(['key2'],keep='last')      #drop from bottom to top    #method1

key1  key2
1    a     2
4    b     3

In [181]:
d.drop_duplicates(keep='last',subset=['key2'])    #method 2

key1  key2
1    a     2
4    b     3

In [184]:
D=d.drop_duplicates(['key1'],keep='last')
D

key1  key2
2    a     3
4    b     3

In [185]:
D.shape

(2, 2)

In [189]:
d=DataFrame({'A':[1,4,7],'B':[2,5,8],'C':[3,6,9]},index=['ny','la','sf'])

In [190]:
d

A  B  C
ny  1  2  3
la  4  5  6
sf  7  8  9

In [196]:
d.rename({'ny':'newyork'})         #default index       #method1     need to pass as dic

A  B  C
newyork  1  2  3
la       4  5  6
sf       7  8  9

In [203]:
d.rename(index={'ny':'newyork'})      #method 2

A  B  C
newyork  1  2  3
la       4  5  6
sf       7  8  9

In [208]:
d.rename({'A':'alpha','B':'beta','C':'gama'},axis=1,inplace=True) #method1   #column rename
d

alpha  beta  gama
ny      1     2     3
la      4     5     6
sf      7     8     9

In [200]:
d.rename(columns={'C':'london'})       #method 2

A  B  london
ny  1  2       3
la  4  5       6
sf  7  8       9

In [202]:
d.rename({'ny':'newyork','sf':'sanfranc','la':'los angles'})  #rename

A  B  C
newyork     1  2  3
los angles  4  5  6
sanfranc    7  8  9

In [212]:
d.rename(index={'ny':'newyork'},columns={'A':'alpha','B':'beta','C':'gama'})   #rename index as well as column

alpha  beta  gama
newyork      1     2     3
la           4     5     6
sf           7     8     9

In [213]:
d.T        #convert row into column and column into row

ny  la  sf
alpha   1   4   7
beta    2   5   8
gama    3   6   9

In [226]:
d=DataFrame(np.arange(1,10).reshape(3,3))

In [215]:
d

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [218]:
s=Series([1,2,3,1,2,3])

In [219]:
s

0    1
1    2
2    3
3    1
4    2
5    3
dtype: int64

In [220]:
s.replace({1:100})

0    100
1      2
2      3
3    100
4      2
5      3
dtype: int64

In [222]:
s.replace({2:200,3:300}) #multiple #method 1   through dic

0      1
1    200
2    300
3      1
4    200
5    300
dtype: int64

In [225]:
s.replace([2,3],[200,300])   #method 2     #through list 
#what we want to replace  #what value we want to assign

0      1
1    200
2    300
3      1
4    200
5    300
dtype: int64

In [227]:
d

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [233]:
d.replace([1,2],[100,200])  #check all value in data and replace

0    1  2
0  100  200  3
1    4    5  6
2    7    8  9

### MAPPING

In [235]:
height={'dheeraj':3,'salil':10,'yamini':20}
height

{'dheeraj': 3, 'salil': 10, 'yamini': 20}

In [239]:
d=DataFrame({'name':['yamini','salil','dheeraj'],'weight':[200,250,51]})

In [240]:
d

name  weight
0   yamini     200
1    salil     250
2  dheeraj      51

In [248]:
d['height']=d['name'].map(height)  #with refrence to name in exe 

In [249]:
d

name  weight  height
0   yamini     200      20
1    salil     250      10
2  dheeraj      51       3

### Merging DATA

## type of merging

1.inner merge
2.outer merge
3.left merge
4.right merge


# ## Method of merging


1 column-column merge

2 columne-index

3 index-column

4 index-index


### column-column merge

## column-column merge




In [29]:
d1=DataFrame({'key':list('xzyzxx'),'data1':list(np.arange(1,7))})
d2=DataFrame({'key':list('qyz'),'data2':list(np.arange(1,4))})

In [30]:
d1

key  data1
0   x      1
1   z      2
2   y      3
3   z      4
4   x      5
5   x      6

In [261]:
d2

key  data2
0   q      1
1   y      2
2   z      3

In [264]:
pd.merge (d1,d2)     #common column row values will be merged   #method1  by default

key  data1  data2
0   z      2      3
1   z      4      3
2   y      3      2

In [265]:
d1.merge(d2)         #method 2

key  data1  data2
0   z      2      3
1   z      4      3
2   y      3      2

In [267]:
pd.merge (d1,d2,on='key')   #method 3   #when multiple common column then define on="on which we want to merge"

key  data1  data2
0   z      2      3
1   z      4      3
2   y      3      2

In [268]:
pd.merge(d1,d2,how='inner')   #default inner join when we will not give command

key  data1  data2
0   z      2      3
1   z      4      3
2   y      3      2

In [269]:
pd.merge(d1,d2,how='outer') #merge both if value then print else null

key  data1  data2
0   x    1.0    NaN
1   x    5.0    NaN
2   x    6.0    NaN
3   z    2.0    3.0
4   z    4.0    3.0
5   y    3.0    2.0
6   q    NaN    1.0

In [270]:
pd.merge(d1,d2,how='left') #merge on base of left on base of left

key  data1  data2
0   x      1    NaN
1   z      2    3.0
2   y      3    2.0
3   z      4    3.0
4   x      5    NaN
5   x      6    NaN

In [272]:
pd.merge(d1,d2,how='right')  #base right column and merge on basse of right

key  data1  data2
0   z    2.0      3
1   z    4.0      3
2   y    3.0      2
3   q    NaN      1

In [277]:
d1=DataFrame({'key':list('xxxyzz'),'data1':list(np.arange(1,7))})
d2=DataFrame({'key':list('yyxxz'),'data2':list(np.arange(1,6))})


In [278]:
d1

key  data1
0   x      1
1   x      2
2   x      3
3   y      4
4   z      5
5   z      6

In [279]:
d2

key  data2
0   y      1
1   y      2
2   x      3
3   x      4
4   z      5

In [280]:
d1.merge(d2)   #output will be same in all merge if both element are same in both data frame

key  data1  data2
0   x      1      3
1   x      1      4
2   x      2      3
3   x      2      4
4   x      3      3
5   x      3      4
6   y      4      1
7   y      4      2
8   z      5      5
9   z      6      5

In [281]:
pd.merge(d1,d2,how='left')

key  data1  data2
0   x      1      3
1   x      1      4
2   x      2      3
3   x      2      4
4   x      3      3
5   x      3      4
6   y      4      1
7   y      4      2
8   z      5      5
9   z      6      5

In [282]:
pd.merge(d1,d2,how='right')

key  data1  data2
0   x      1      3
1   x      2      3
2   x      3      3
3   x      1      4
4   x      2      4
5   x      3      4
6   y      4      1
7   y      4      2
8   z      5      5
9   z      6      5

In [283]:
pd.merge(d1,d2,how='outer')

key  data1  data2
0   x      1      3
1   x      1      4
2   x      2      3
3   x      2      4
4   x      3      3
5   x      3      4
6   y      4      1
7   y      4      2
8   z      5      5
9   z      6      5

## column-index merge

In [295]:
d1=DataFrame({'key':list('xxyz'),'data':list(np.arange(1,5))})
d2=DataFrame({'dataset':list(np.arange(1,4))},index=list('xab'))


In [296]:
d1

key  data
0   x     1
1   x     2
2   y     3
3   z     4

In [297]:
d2

dataset
x        1
a        2
b        3

In [299]:
pd.merge(d1,d2,left_on='key',right_index=True) #left_on for column name present in left data set and right_index is for index of right data set

key  data  dataset
0   x     1        1
1   x     2        1

In [300]:
pd.merge(d1,d2,left_on='key',right_index=True,how='outer')

key  data  dataset
0   x   1.0      1.0
1   x   2.0      1.0
2   y   3.0      NaN
3   z   4.0      NaN
3   a   NaN      2.0
3   b   NaN      3.0

In [301]:
pd.merge(d1,d2,left_on='key',right_index=True,how='left')

key  data  dataset
0   x     1      1.0
1   x     2      1.0
2   y     3      NaN
3   z     4      NaN

In [302]:
pd.merge(d1,d2,left_on='key',right_index=True,how='right')

key  data  dataset
0   x   1.0        1
1   x   2.0        1
3   a   NaN        2
3   b   NaN        3

### INDEX-COLUMN

In [306]:
pd.merge(d2,d1,right_on='key',left_index=True,how='right')   ## INDEX-COlUMN

dataset key  data
0      1.0   x     1
1      1.0   x     2
2      NaN   y     3
3      NaN   z     4

In [307]:
pd.merge(d2,d1,right_on='key',left_index=True,how='left')   ## INDEX-COlUMN

dataset key  data
0        1   x   1.0
1        1   x   2.0
3        2   a   NaN
3        3   b   NaN

In [308]:
pd.merge(d2,d1,right_on='key',left_index=True,how='outer')   ## INDEX-COlUMN

dataset key  data
0      1.0   x   1.0
1      1.0   x   2.0
3      2.0   a   NaN
3      3.0   b   NaN
2      NaN   y   3.0
3      NaN   z   4.0

In [309]:
pd.merge(d2,d1,right_on='key',left_index=True)   ## INDEX-COlUMN

dataset key  data
0        1   x     1
1        1   x     2

### INDEX-INDEX MERGE

In [310]:
d1=DataFrame({'data1':list(np.arange(1,4))},index=list('xyz'))
d2=DataFrame({'data2':list(np.arange(1,5))},index=list('xyab'))


In [311]:
d1


data1
x      1
y      2
z      3

In [312]:
d2

data2
x      1
y      2
a      3
b      4

In [313]:
pd.merge(d1,d2,left_index=True,right_index=True)     #inner join only common value will be merge

data1  data2
x      1      1
y      2      2

In [315]:
pd.merge(d1,d2,left_index=True,right_index=True,how='outer')

data1  data2
a    NaN    3.0
b    NaN    4.0
x    1.0    1.0
y    2.0    2.0
z    3.0    NaN

In [316]:
pd.merge(d1,d2,left_index=True,right_index=True,how='left')

data1  data2
x      1    1.0
y      2    2.0
z      3    NaN

In [317]:
pd.merge(d1,d2,left_index=True,right_index=True,how='right')

data1  data2
x    1.0      1
y    2.0      2
a    NaN      3
b    NaN      4

In [367]:
d1=DataFrame(np.arange(1,26).reshape(5,5),index=list('wzyzq'),columns=list('abcde'))


In [368]:
d1

a   b   c   d   e
w   1   2   3   4   5
z   6   7   8   9  10
y  11  12  13  14  15
z  16  17  18  19  20
q  21  22  23  24  25

In [369]:
d1.drop('w')    #dirctly drop element through drop fun #default on index base

a   b   c   d   e
z   6   7   8   9  10
y  11  12  13  14  15
z  16  17  18  19  20
q  21  22  23  24  25

In [370]:
d1.drop('e',axis=1)  #for column base

a   b   c   d
w   1   2   3   4
z   6   7   8   9
y  11  12  13  14
z  16  17  18  19
q  21  22  23  24

In [391]:
d1.drop(columns=d1.columns[[0,1]])

c   d   e
w   3   4   5
z   8   9  10
y  13  14  15
z  18  19  20
q  23  24  25

In [376]:
d1.drop(d1.columns[0],axis=1)

b   c   d   e
w   2   3   4   5
z   7   8   9  10
y  12  13  14  15
z  17  18  19  20
q  22  23  24  25

In [379]:
d1.drop(d1.columns[[1,3]],axis=1)

a   c   e
w   1   3   5
z   6   8  10
y  11  13  15
z  16  18  20
q  21  23  25

In [378]:
d1.drop(d1.index[[1,3]],axis=0)

a   b   c   d   e
w   1   2   3   4   5
y  11  12  13  14  15
q  21  22  23  24  25

### PIVOT

In [399]:
d=DataFrame({'variable':list('aaabbbcccddd'),'value':[1,2,3,1,2,3,1,2,3,1,2,3],'data':np.random.rand(12)})

In [400]:
d

variable  value      data
0         a      1  0.859019
1         a      2  0.568193
2         a      3  0.035130
3         b      1  0.693992
4         b      2  0.943618
5         b      3  0.779719
6         c      1  0.908861
7         c      2  0.735396
8         c      3  0.274924
9         d      1  0.874200
10        d      2  0.338799
11        d      3  0.442853

In [404]:
 d.pivot('variable','value','data') #pivot use for better mapping
                                          #metghod1

value            1         2         3
variable                              
a         0.859019  0.568193  0.035130
b         0.693992  0.943618  0.779719
c         0.908861  0.735396  0.274924
d         0.874200  0.338799  0.442853

In [405]:
pd.pivot(d,'variable','value','data')
                                             #methopd 2

value            1         2         3
variable                              
a         0.859019  0.568193  0.035130
b         0.693992  0.943618  0.779719
c         0.908861  0.735396  0.274924
d         0.874200  0.338799  0.442853

In [406]:
 d.pivot('value','variable','data')        #for wrangling data

variable         a         b         c         d
value                                           
1         0.859019  0.693992  0.908861  0.874200
2         0.568193  0.943618  0.735396  0.338799
3         0.035130  0.779719  0.274924  0.442853

In [407]:
 d.pivot('data','value','variable')        #data will not priorly as it has 12 element and value is variable only 3 & 4

value       1    2    3
data                   
0.035130  NaN  NaN    a
0.274924  NaN  NaN    c
0.338799  NaN    d  NaN
0.442853  NaN  NaN    d
0.568193  NaN    a  NaN
0.693992    b  NaN  NaN
0.735396  NaN    c  NaN
0.779719  NaN  NaN    b
0.859019    a  NaN  NaN
0.874200    d  NaN  NaN
0.908861    c  NaN  NaN
0.943618  NaN    b  NaN

In [413]:
d=DataFrame({'age':np.random.randint(1,31,15)})

In [414]:
d

age
0    14
1    18
2    22
3    21
4    19
5    30
6     7
7    18
8    28
9     6
10   24
11   18
12    7
13    3
14   28

In [416]:
d['gender']=list('mmmmmfffffmfmfm')
d['city']=list('dngndgndngngndg')

In [417]:
d

age gender city
0    14      m    d
1    18      m    n
2    22      m    g
3    21      m    n
4    19      m    d
5    30      f    g
6     7      f    n
7    18      f    d
8    28      f    n
9     6      f    g
10   24      m    n
11   18      f    g
12    7      m    n
13    3      f    d
14   28      m    g

In [426]:
d.pivot_table(index='gender',columns='city',values='age')    #take average of age 

city       d     g     n
gender                  
f       10.5  18.0  17.5
m       16.5  25.0  17.5

In [429]:
d.pivot_table(index='gender',columns='city',values='age',aggfunc='sum')   #sum of values

city     d   g   n
gender            
f       21  54  35
m       33  50  70

In [430]:
d['age'].skew()   # EDA

-0.30701861098789984

In [431]:
d['age'].kurt()

-0.9755116254859928

In [432]:
d['age'].kurtosis()

-0.9755116254859928