In [5]:
test_array = [10, 11.5, 12, 13.5, 14,15]
test_array[1:2]

[11.5]

In [1]:
import numpy as np
demo_array = np.arange(10,21)

subset_demo_array = demo_array[0:7]

subset_demo_array[:]= 101

subset_demo_array

array([101, 101, 101, 101, 101, 101, 101])

In [5]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))

demo_matrix[2,3]

39

In [3]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))
demo_matrix


array([[13, 35, 74, 48],
       [23, 37, 37, 38],
       [73, 39, 93, 39]])

In [4]:
demo_matrix[:, (1,2)]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [9]:
demo_array=np.arange(0,10)
print(demo_array)
 
print(demo_array <3)           #return as boolean 

print(demo_array[demo_array <6])    #return as less than 6 value

print(np.max(demo_array))

[0 1 2 3 4 5 6 7 8 9]
[ True  True  True False False False False False False False]
[0 1 2 3 4 5]
9


In [7]:
np.arange(0,22,6)

array([ 0,  6, 12, 18])

In [14]:
demo_array = np.arange(10,21)

subset_demo_array = demo_array[0:7]
subset_demo_array[:]= 101
subset_demo_array

array([101, 101, 101, 101, 101, 101, 101])

In [9]:
a=np.array([10,20,15,100])

In [10]:
b=a.argsort()         #sorting by value
b

array([0, 2, 1, 3], dtype=int64)

In [33]:
### SLICING

a=np.arange(1,50).reshape(7,7)
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [34]:
a[1,0]

8

In [49]:
a[3,2:5]

array([24, 25, 26])

In [36]:
a[2,:]    #a[2]

array([15, 16, 17, 18, 19, 20, 21])

In [38]:
a[2:6]

array([[15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42]])

In [41]:
a[:,1]

array([ 2,  9, 16, 23, 30, 37, 44])

In [45]:
a[:,2:5]

array([[ 3,  4,  5],
       [10, 11, 12],
       [17, 18, 19],
       [24, 25, 26],
       [31, 32, 33],
       [38, 39, 40],
       [45, 46, 47]])

In [55]:
a[[2,3]]

array([[15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28]])

In [56]:
a[:,[2,5]]

array([[ 3,  6],
       [10, 13],
       [17, 20],
       [24, 27],
       [31, 34],
       [38, 41],
       [45, 48]])

In [57]:
a[0,[2,5]]

array([3, 6])

# DAY-06  PANDAS

### SERIES:--

In [10]:
import pandas as pd
import numpy as np

In [11]:
from pandas import Series

In [3]:
s1=Series([10,20,30,40])           #in series we give index which is not in array
s1                 #series :-  indexes  value

0    10
1    20
2    30
3    40
dtype: int64

In [80]:
 s1=Series([10,20,30,40],index=['A','B','C','D'])       # method 1

In [81]:
s1               # name    indexes    value

A    10
B    20
C    30
D    40
dtype: int64

In [10]:
s1=Series([10,20,30,40],index=list('ABCD'))         # method 2
s1

A    10
B    20
C    30
D    40
dtype: int64

In [94]:
s1.values

array([10, 20, 30, 40], dtype=int64)

In [4]:
s2=Series(['chandigarh','banaras','mumbai'],index=list('ABC'))
s2              
#index    #values

A    chandigarh
B       banaras
C        mumbai
dtype: object

In [92]:
s2.index

Index(['A', 'B', 'C'], dtype='object')

In [93]:
s2.values

array(['chandigarh', 'banaras', 'mumbai'], dtype=object)

In [13]:
s1=Series(np.random.randint(1,101,5),index=list('ABCDE'))
s1            # pass list,ARRAY,INT

A    62
B    20
C    72
D    19
E    94
dtype: int32

In [7]:
s1=Series(np.arange(0,9).reshape(3,3),index=list('abc'))
s1                  #not work in 2d  #we have to use dataframe here

Exception: Data must be 1-dimensional

In [13]:
dic={"a":100,"b":200,"c":300}
dic

{'a': 100, 'b': 200, 'c': 300}

In [16]:
Series(dic)

a    100
b    200
c    300
dtype: int64

In [21]:
s1=Series(np.random.randint(1,101,3),index=[3,0,2])
s1

3     7
0    20
2    77
dtype: int32

In [22]:
s1[1]          #fails due to same location is not callable bcoz of same indexing

KeyError: 1

In [23]:
s1=Series(np.random.randint(1,101,5),index=list('ABCDE'))
s1

A    91
B    78
C    41
D    15
E    46
dtype: int32

In [24]:
#SELECTING entries in series:

In [25]:
s1[0]             #grab by method

91

In [26]:
s1['A']            # grab by label

91

In [27]:
s1[['A','D']]     #grab by multiple labels   list of list

A    91
D    15
dtype: int32

In [28]:
s1[2:4]            # grab by range

C    41
D    15
dtype: int32

In [29]:
s1[[2,4]]       #grab by multiple range through list of list

C    41
E    46
dtype: int32

In [30]:
s1[2:]

C    41
D    15
E    46
dtype: int32

In [31]:
                         # GRAB BY LOGIC
s1>50

A     True
B     True
C    False
D    False
E    False
dtype: bool

In [32]:
s1[s1>50]         #grab by logic or bool method if condition is true then it will return output and rest will separate

A    91
B    78
dtype: int32

In [33]:
s1+100       #airthmatic operators in pandas

A    191
B    178
C    141
D    115
E    146
dtype: int32

In [34]:
s1-100

A    -9
B   -22
C   -59
D   -85
E   -54
dtype: int32

In [35]:
s1*100

A    9100
B    7800
C    4100
D    1500
E    4600
dtype: int32

In [36]:
s1/0.25

A    364.0
B    312.0
C    164.0
D     60.0
E    184.0
dtype: float64

In [37]:
s1**2

A    8281
B    6084
C    1681
D     225
E    2116
dtype: int32

### RE-INDEXING:----

In [29]:
s1=Series(["india","bhutan","nepal"],index=["1","5","10"])      #indexing
s1                                                              #method 1

1      india
5     bhutan
10     nepal
dtype: object

In [31]:
s1=Series(["india","bhutan","nepal"],index=("1","5","10"))       #passing tuple
s1                                                              #method 2

1      india
5     bhutan
10     nepal
dtype: object

In [131]:
s1=Series({1:"india",5:"bhutan",10:"nepal"})                      #dic method
s1                                                              #method 3

1      india
5     bhutan
10     nepal
dtype: object

In [139]:
s1.reindex(range(15))        # reindex change original into mapped like 1,5,10 and rest are nun

#if output is showing then changes are temporary  but if as command it doesnt show output that means it is permanent

0        NaN
1      india
2        NaN
3        NaN
4        NaN
5     bhutan
6        NaN
7        NaN
8        NaN
9        NaN
10     nepal
11       NaN
12       NaN
13       NaN
14       NaN
dtype: object

In [140]:
# specially for nan value in numpy , we use np.nan

In [146]:
s1.reindex(range(14),method='ffill')          #forward fill is fill forwardly fill with values which is given like at 1 india

0        NaN
1      india
2      india
3      india
4      india
5     bhutan
6     bhutan
7     bhutan
8     bhutan
9     bhutan
10     nepal
11     nepal
12     nepal
13     nepal
dtype: object

In [148]:
s1.reindex(range(15),method='bfill')     # backwardly fill

0      india
1      india
2     bhutan
3     bhutan
4     bhutan
5     bhutan
6      nepal
7      nepal
8      nepal
9      nepal
10     nepal
11       NaN
12       NaN
13       NaN
14       NaN
dtype: object

In [150]:
s1.reindex(range(14),method="nearest")        # nearest indexs taking same value  like 3 is b/w 1 and 5 so it will take further value as bhutan a/c to nearest further fill value

0      india
1      india
2      india
3     bhutan
4     bhutan
5     bhutan
6     bhutan
7     bhutan
8      nepal
9      nepal
10     nepal
11     nepal
12     nepal
13     nepal
dtype: object

### DATA FRAMES:---

In [7]:
from pandas import Series,DataFrame       # camel casing in DataFrame 

In [8]:
from pandas import Series as s ,DataFrame as d  

In [40]:
df1=DataFrame(np.arange(1,26).reshape(5,5))   #create data through numpy array and then do modulation through pandas dataframe
df1

0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20
4  21  22  23  24  25

In [18]:
df1[0:1]       #by default select rows as column not given

0  1  2  3  4
0  1  2  3  4  5

In [19]:
np.arange(1,26)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [20]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [41]:
df1=DataFrame(np.arange(1,26).reshape(5,5),index=list("abcde"),columns=list('bhfsd'))      #renaming indexs
df1

b   h   f   s   d
a   1   2   3   4   5
b   6   7   8   9  10
c  11  12  13  14  15
d  16  17  18  19  20
e  21  22  23  24  25

In [179]:
df1=DataFrame(np.arange(1,26).reshape(5,5),index=list("abcde"),columns=list("wxyzg"))      #rename column names
df1

w   x   y   z   g
a   1   2   3   4   5
b   6   7   8   9  10
c  11  12  13  14  15
d  16  17  18  19  20
e  21  22  23  24  25

In [185]:
df1["w"]         #fetch column

a     1
b     6
c    11
d    16
e    21
Name: w, dtype: int32

In [188]:
df1[["w","z"]]       #fetch multiple column

w   z
a   1   4
b   6   9
c  11  14
d  16  19
e  21  24

In [ ]:
#fetching row ...

In [200]:
df1=DataFrame({'a':[1,2,3,45],'b':[22,566,45,45]},index=list("qwer"))
df1              # when dataframe in dic method ,dictionary key converted into column name automatically but we need to indexing for rows but in series it will suppose to row name

a    b
q   1   22
w   2  566
e   3   45
r  45   45

In [201]:
df1=DataFrame({'a':[1,2,3,43,4],'b':list("abcde")},index=list("qwert"))
df1         #can pass two catogary data in a single frame 

a  b
q   1  a
w   2  b
e   3  c
r  43  d
t   4  e

In [12]:
df1=DataFrame({'name':["tcs","wipro","infosys","google","yahoo"],"price":[200,300,700,1200,300]}) #default


#method 1

In [13]:
df1

name  price
0      tcs    200
1    wipro    300
2  infosys    700
3   google   1200
4    yahoo    300

In [33]:
df1=DataFrame({'name':["tcs","wipro","infosys","google","yahoo"],"price":[200,300,700,1200,300]},index=list("abcde"))  #indexed

In [34]:
df1

name  price
a      tcs    200
b    wipro    300
c  infosys    700
d   google   1200
e    yahoo    300

In [43]:
df1.iloc[2:4]

name  price
c  infosys    700
d   google   1200

In [21]:
name=["tcs","wipro","infosys","google","yahoo"]
price=[200,300,700,1200,300]                                #method 2
df1=DataFrame(zip(name,price),columns=["name","price"])
df1

name  price
0      tcs    200
1    wipro    300
2  infosys    700
3   google   1200
4    yahoo    300

In [22]:
df1['city2']='gurgaon'
df1              # assign same values

name  price    city2
0      tcs    200  gurgaon
1    wipro    300  gurgaon
2  infosys    700  gurgaon
3   google   1200  gurgaon
4    yahoo    300  gurgaon

In [23]:
df1['city']=['gurgaon','gurgaon2','gurgaon3','gurgaon4','gurgaon5']
df1                          # for different values

name  price    city2      city
0      tcs    200  gurgaon   gurgaon
1    wipro    300  gurgaon  gurgaon2
2  infosys    700  gurgaon  gurgaon3
3   google   1200  gurgaon  gurgaon4
4    yahoo    300  gurgaon  gurgaon5

In [24]:
df1['price']+10


0     210
1     310
2     710
3    1210
4     310
Name: price, dtype: int64

In [25]:
df1['price']=df1['price']+10
df1

name  price    city2      city
0      tcs    210  gurgaon   gurgaon
1    wipro    310  gurgaon  gurgaon2
2  infosys    710  gurgaon  gurgaon3
3   google   1210  gurgaon  gurgaon4
4    yahoo    310  gurgaon  gurgaon5

In [26]:
df1['discount']=0.9*df1['price']
df1

name  price    city2      city  discount
0      tcs    210  gurgaon   gurgaon     189.0
1    wipro    310  gurgaon  gurgaon2     279.0
2  infosys    710  gurgaon  gurgaon3     639.0
3   google   1210  gurgaon  gurgaon4    1089.0
4    yahoo    310  gurgaon  gurgaon5     279.0

In [27]:
df1['price']      #grab by column

0     210
1     310
2     710
3    1210
4     310
Name: price, dtype: int64

In [28]:
df1[['name','discount']]    #grab by multiple column name

name  discount
0      tcs     189.0
1    wipro     279.0
2  infosys     639.0
3   google    1089.0
4    yahoo     279.0

In [29]:
df1[1:3]      #index row  #grab by range

name  price    city2      city  discount
1    wipro    310  gurgaon  gurgaon2     279.0
2  infosys    710  gurgaon  gurgaon3     639.0

In [30]:
df1['region','section']='ncr','sectors'
df1                       # we can't do for adding multiple columns ,if want then need to use indexing

ValueError: Length of values does not match length of index

In [31]:
df1.ix[:,"price"]      #deprecated means not in use now

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


0     210
1     310
2     710
3    1210
4     310
Name: price, dtype: int64

###    .iloc   and  .loc  fun 

In [32]:
#iloc 

df1

name  price    city2      city  discount
0      tcs    210  gurgaon   gurgaon     189.0
1    wipro    310  gurgaon  gurgaon2     279.0
2  infosys    710  gurgaon  gurgaon3     639.0
3   google   1210  gurgaon  gurgaon4    1089.0
4    yahoo    310  gurgaon  gurgaon5     279.0

In [45]:
df1[0]   #work on array only

KeyError: 0

In [15]:
df1.iloc[0]

name     tcs
price    200
Name: 0, dtype: object

In [18]:
df1.loc[0,1]

TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [1] of <class 'int'>

In [16]:
df1.iloc[1:4]

name  price
1    wipro    300
2  infosys    700
3   google   1200

In [47]:
df1.iloc[0,2:4]         #iloc is locked by lebel

discount    189
Name: 0, dtype: object

In [261]:
df1.iloc[1:3,0:2]

name  price
1    wipro    320
2  infosys    720

In [268]:
df1.iloc[[1,4],0:2]          #iloc fun

name  price
1  wipro    320
4  yahoo    320

In [50]:
#loc fun

df1

name  price  discount    city2
0      tcs    210     189.0  gurgaon
1    wipro    310     279.0  gurgaon
2  infosys    710     639.0  gurgaon
3   google   1210    1089.0  gurgaon
4    yahoo    310     279.0  gurgaon

In [51]:
df1.index

RangeIndex(start=0, stop=5, step=1)

In [52]:
df1.columns

Index(['name', 'price', 'discount', 'city2'], dtype='object')

In [273]:
df1['price'].values

array([ 220,  320,  720, 1220,  320], dtype=int64)

In [53]:
df1.index=list('abcde')

In [54]:
df1

name  price  discount    city2
a      tcs    210     189.0  gurgaon
b    wipro    310     279.0  gurgaon
c  infosys    710     639.0  gurgaon
d   google   1210    1089.0  gurgaon
e    yahoo    310     279.0  gurgaon

In [55]:
df1.loc['a']

name            tcs
price           210
discount        189
city2       gurgaon
Name: a, dtype: object

In [277]:
df1.loc[:,'name']

a        tcs
b      wipro
c    infosys
d     google
e      yahoo
Name: name, dtype: object

In [279]:
df1.loc['b','name']            #loc by column

'wipro'

In [281]:
df1.loc[:,['name','city']]

name      city
a      tcs   gurgaon
b    wipro  gurgaon2
c  infosys  gurgaon3
d   google  gurgaon4
e    yahoo  gurgaon5

In [284]:
df1.loc[['a','d'],['name','city']]

name      city
a     tcs   gurgaon
d  google  gurgaon4

In [287]:
df1.loc['d','name']

'google'

In [56]:
df1=DataFrame(np.random.rand(1,101))
df1

0         1         2        3         4        5         6    \
0  0.681332  0.010776  0.130597  0.97211  0.906166  0.15003  0.363345   

        7         8        9    ...       91        92        93        94   \
0  0.973622  0.275004  0.25694  ...  0.495753  0.409074  0.495505  0.189018   

        95        96        97        98        99       100  
0  0.519658  0.983646  0.802384  0.997089  0.452025  0.63107  

[1 rows x 101 columns]

In [59]:
s1=Series(np.random.randint(1,101,10))
s1

0    36
1    68
2    32
3     8
4    24
5    64
6    66
7    82
8    53
9    14
dtype: int32

In [60]:
s1.sort_values()      #sort by value so indexes are according to value

3     8
9    14
4    24
2    32
0    36
8    53
5    64
6    66
1    68
7    82
dtype: int32

In [61]:
s1.sort_values(ascending=False)

7    82
1    68
6    66
5    64
8    53
0    36
2    32
4    24
9    14
3     8
dtype: int32

In [62]:
s1.sort_values(ascending=False,inplace=True)        #inplace is use for permanent changes

#now it will sort as indexes

In [63]:
s1

7    82
1    68
6    66
5    64
8    53
0    36
2    32
4    24
9    14
3     8
dtype: int32

In [67]:
s1.sort_index()     #sort according to indexes

0    36
1    68
2    32
3     8
4    24
5    64
6    66
7    82
8    53
9    14
dtype: int32

In [65]:
s1.sort_index(ascending=False)          #descending 

9    14
8    53
7    82
6    66
5    64
4    24
3     8
2    32
1    68
0    36
dtype: int32

In [66]:
df1=DataFrame(np.arange(1,101,10))

In [322]:
df1

0
0   1
1  11
2  21
3  31
4  41
5  51
6  61
7  71
8  81
9  91

In [8]:
df1=DataFrame({'score':np.random.randint(1,101,10)},index=list('asdfghjklp'))

In [9]:
df1

score
a     33
s     63
d     39
f     89
g     99
h     86
j     49
k     60
l     44
p     78

In [347]:
df1.sort_values(by='score')    #sorting

score
0      8
8     25
7     29
1     31
2     31
9     52
6     78
5     90
3     94
4     98

In [348]:
df1.sort_values(by='score',ascending=False)    #descending order

score
4     98
3     94
5     90
6     78
9     52
1     31
2     31
7     29
8     25
0      8

In [349]:
df1.sort_index()

score
0      8
1     31
2     31
3     94
4     98
5     90
6     78
7     29
8     25
9     52

In [68]:
df1['score2']=np.random.randint(1,101,10)
df1

0  score2
0   1      68
1  11      77
2  21      40
3  31      18
4  41      34
5  51      78
6  61      29
7  71      87
8  81      51
9  91      30

In [69]:
df1.iloc[:2,0]=90
df1.iloc[2:5,0]=50

In [367]:
df1

score  score2
0     90      90
1     90      90
2     50      71
3     50      77
4     50       5
5     90      71
6     78      38
7     29      25
8     25      69
9     52      53

In [369]:
df1.sort_values(by=['score','score2'])

score  score2
8     25      90
7     29      29
4     50       2
2     50      55
3     50      65
9     52       2
6     78       8
0     90       4
1     90      12
5     90      51

In [374]:
df1.sort_values(by=['score','score2'],ascending=False)

score  score2
5     90      51
1     90      12
0     90       4
6     78       8
9     52       2
3     50      65
2     50      55
4     50       2
7     29      29
8     25      90

In [378]:
df1.sort_values(by=[['score',ascending=True],['score2',ascending=False]])  #wrong for one in ascending aand one in decending

SyntaxError: invalid syntax (<ipython-input-378-cc20d656024a>, line 1)

In [380]:
df1.sort_values(by=['score','score2'],ascending=[False,True])  #one in decending and second on accending

score  score2
0     90       4
1     90      12
5     90      51
6     78       8
9     52       2
4     50       2
2     50      55
3     50      65
7     29      29
8     25      90

In [382]:
df1.sort_values(by=['score','score2'],ascending=[True,False])  #one in ascending and second on descending

score  score2
8     25      90
7     29      29
3     50      65
2     50      55
4     50       2
9     52       2
6     78       8
5     90      51
1     90      12
0     90       4

In [424]:
df1['score3']=np.random.randint(1,101,10)
df1

score  score2  score3
0     70       4      92
1     70      12       7
2     70      55      47
3     70      65      53
4     70       2      75
5     90      51      11
6     78       8       2
7     29      29      77
8     25      90      12
9     52       2      35

In [439]:
df1.iloc[3:4,1]=75
df1

score  score2  score3
0     70       4      92
1     70      12       7
2     70      55      47
3     70      75      53
4     70       2      75
5     90      51      75
6     78       8       2
7     29      29      77
8     25      90      12
9     52       2      35

In [435]:
df1.sort_values(by=['score','score2','score3'],ascending=[True,False,True])

score  score2  score3
8     25      90      12
7     29      29      77
9     52       2      35
3     70      65      53
2     70      55      47
1     70      12       7
0     70       4      92
4     70       2      75
6     78       8       2
5     90      51      75

### RANKS

In [55]:
df2=DataFrame({'name':list('abcdesghij'),'score':np.random.randint(1,101,10)})
df2

name  score
0    a     16
1    b     28
2    c     87
3    d     77
4    e     97
5    s     60
6    g      3
7    h     53
8    i     81
9    j     38

In [57]:
df2.iloc[:2,1]=80
df2

name  score
0    a     80
1    b     80
2    c     87
3    d     77
4    e     97
5    s     60
6    g      3
7    h     53
8    i     81
9    j     38

In [418]:
#ranks are of 5 types

In [54]:
#### 1)  AVERAGE RANK



df2['RANK avg']=df2['score'].rank()     # average rank which will take average of same values and print as average and further
df2

name  score  RANK avg
0    a     80       8.5
1    b     80       8.5
2    c     42       6.0
3    d      3       1.0
4    e     24       4.0
5    s     94      10.0
6    g     20       3.0
7    h     40       5.0
8    i     79       7.0
9    j      7       2.0

In [55]:
df2['Rank avg d']=df2['score'].rank(ascending=False)     #descending rank
df2

name  score  RANK avg  Rank avg d
0    a     80       8.5         2.5
1    b     80       8.5         2.5
2    c     42       6.0         5.0
3    d      3       1.0        10.0
4    e     24       4.0         7.0
5    s     94      10.0         1.0
6    g     20       3.0         8.0
7    h     40       5.0         6.0
8    i     79       7.0         4.0
9    j      7       2.0         9.0

In [56]:
#### 2) MINUMUM RANK



df2['Rank min']=df2['score'].rank(method='min')
df2

name  score  RANK avg  Rank avg d  Rank min
0    a     80       8.5         2.5       8.0
1    b     80       8.5         2.5       8.0
2    c     42       6.0         5.0       6.0
3    d      3       1.0        10.0       1.0
4    e     24       4.0         7.0       4.0
5    s     94      10.0         1.0      10.0
6    g     20       3.0         8.0       3.0
7    h     40       5.0         6.0       5.0
8    i     79       7.0         4.0       7.0
9    j      7       2.0         9.0       2.0

In [57]:
### 3) MAX RANK



df2['Rank max']=df2['score'].rank(method='max')
df2

name  score  RANK avg  Rank avg d  Rank min  Rank max
0    a     80       8.5         2.5       8.0       9.0
1    b     80       8.5         2.5       8.0       9.0
2    c     42       6.0         5.0       6.0       6.0
3    d      3       1.0        10.0       1.0       1.0
4    e     24       4.0         7.0       4.0       4.0
5    s     94      10.0         1.0      10.0      10.0
6    g     20       3.0         8.0       3.0       3.0
7    h     40       5.0         6.0       5.0       5.0
8    i     79       7.0         4.0       7.0       7.0
9    j      7       2.0         9.0       2.0       2.0

In [58]:
#### DANSE RANK


                # dense will take the min rank and will not skip the max rank tehrefore chances that the highest rank and total no. of entries are not might be same
df2['dense Rank']=df2['score'].rank(method='dense')
df2

name  score  RANK avg  Rank avg d  Rank min  Rank max  dense Rank
0    a     80       8.5         2.5       8.0       9.0         8.0
1    b     80       8.5         2.5       8.0       9.0         8.0
2    c     42       6.0         5.0       6.0       6.0         6.0
3    d      3       1.0        10.0       1.0       1.0         1.0
4    e     24       4.0         7.0       4.0       4.0         4.0
5    s     94      10.0         1.0      10.0      10.0         9.0
6    g     20       3.0         8.0       3.0       3.0         3.0
7    h     40       5.0         6.0       5.0       5.0         5.0
8    i     79       7.0         4.0       7.0       7.0         7.0
9    j      7       2.0         9.0       2.0       2.0         2.0

In [59]:
#####  4) first come first serve RANK(fcfs)

                  # when same marks are same then it will focus on fcfs

df2['first']=df2['score'].rank(method='first')
df2


name  score  RANK avg  Rank avg d  Rank min  Rank max  dense Rank  first
0    a     80       8.5         2.5       8.0       9.0         8.0    8.0
1    b     80       8.5         2.5       8.0       9.0         8.0    9.0
2    c     42       6.0         5.0       6.0       6.0         6.0    6.0
3    d      3       1.0        10.0       1.0       1.0         1.0    1.0
4    e     24       4.0         7.0       4.0       4.0         4.0    4.0
5    s     94      10.0         1.0      10.0      10.0         9.0   10.0
6    g     20       3.0         8.0       3.0       3.0         3.0    3.0
7    h     40       5.0         6.0       5.0       5.0         5.0    5.0
8    i     79       7.0         4.0       7.0       7.0         7.0    7.0
9    j      7       2.0         9.0       2.0       2.0         2.0    2.0

In [60]:
df1=DataFrame({'name':list('abcdesghij'),'score':np.random.randint(1,101,10)})
df1

name  score
0    a     71
1    b     35
2    c     53
3    d      4
4    e     79
5    s     64
6    g     85
7    h     42
8    i     65
9    j     71

In [61]:
df1['gender']=['f','m','m','f','m','f','m','m','f','m']   #method 1

In [63]:
df1

name  score gender
0    a     71      f
1    b     35      m
2    c     53      m
3    d      4      f
4    e     79      m
5    s     64      f
6    g     85      m
7    h     42      m
8    i     65      f
9    j     71      m

In [445]:
df1['gender']=list('mfmmfmfmfm')

In [446]:
df1

name  score gender
0    a     47      m
1    b     46      f
2    c     91      m
3    d     60      m
4    e     25      f
5    s      3      m
6    g     95      f
7    h     80      m
8    i     59      f
9    j     66      m

In [449]:
#df1=pd.read_csv('Filename.csv') to read data


# must python data and data in same folder

In [450]:
df1.head()

name  score gender
0    a     47      m
1    b     46      f
2    c     91      m
3    d     60      m
4    e     25      f

In [451]:
df1.head(2)


name  score gender
0    a     47      m
1    b     46      f

In [452]:
df1.tail()

name  score gender
5    s      3      m
6    g     95      f
7    h     80      m
8    i     59      f
9    j     66      m

In [453]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
name      10 non-null object
score     10 non-null int32
gender    10 non-null object
dtypes: int32(1), object(2)
memory usage: 280.0+ bytes


In [454]:
df1.describe()

score
count  10.000000
mean   57.200000
std    28.642626
min     3.000000
25%    46.250000
50%    59.500000
75%    76.500000
max    95.000000

In [459]:
df1

name  score gender
0    a     47      m
1    b     46      f
2    c     91      m
3    d     60      m
4    e     25      f
5    s      3      m
6    g     95      f
7    h     80      m
8    i     59      f
9    j     66      m

In [472]:
df1['gender'].value_counts()   # method 1

m    6
f    4
Name: gender, dtype: int64

In [479]:
c=0                    # method 2
d=0
for i in df1['gender']:
    if i == 'm':
        c=c+1
    else:
        d=d+1
        
print(c)
print(d)

6
4


In [481]:

df1[df1['gender']=='f']

name  score gender
1    b     46      f
4    e     25      f
6    g     95      f
8    i     59      f

In [65]:
df1[df1['gender']=='m']

name  score gender
1    b     35      m
2    c     53      m
4    e     79      m
6    g     85      m
7    h     42      m
9    j     71      m

In [483]:
(df1['gender']=='m').sum()      # method 3

6

In [486]:
df1['score']

0    47
1    46
2    91
3    60
4    25
5     3
6    95
7    80
8    59
9    66
Name: score, dtype: int32

In [485]:
df1['score'].max()

95

In [487]:
df1['score'].min()

3

In [488]:
df1['score'].mean()

57.2

In [489]:
df1['score'].var()

820.4

In [490]:
df1['score'].std()

28.642625577973817